  ## Ejercicios prácticos

  ### Escribe código Python con Numpy para realizar las siguientes operaciones:


In [4]:
import numpy as np

1. Determinar si ninguno de los elementos de un arreglo es cero.


In [13]:
arreglo_con_ceros = np.array([0,1,2,3,4])
arreglo_sin_ceros = np.array([1,2,3,4,5])
print( "el cero se encuentra en la posición:", np.where(arreglo_con_ceros == 0))
print( "el cero se encuentra en la posición:", np.where(arreglo_sin_ceros == 0))

el cero se encuentra en la posición: (array([0]),)
el cero se encuentra en la posición: (array([], dtype=int64),)


2. Determinar si un arreglo contiene algún elemnto que no sea cero.

In [14]:
print( "el cero se encuentra en la posición:", np.nonzero(arreglo_con_ceros))
print( "el cero se encuentra en la posición:", np.nonzero(arreglo_sin_ceros))

el cero se encuentra en la posición: (array([1, 2, 3, 4]),)
el cero se encuentra en la posición: (array([0, 1, 2, 3, 4]),)


3. Analizar un arreglo de numpy y determinar en sus elementos si existen valores que sean infinitos o valores no numéricos (NaN).

In [26]:
arreglo_nan_inf = np.array([1, 2, 3, 4, np.nan, 5, np.nan, 6, np.inf]).reshape((3,3))
arreglo_nan_inf

array([[ 1.,  2.,  3.],
       [ 4., nan,  5.],
       [nan,  6., inf]])

In [31]:
np.isnan(arreglo_nan_inf)
print(np.isnan(arreglo_nan_inf))
arreglo_nan = np.where(np.isnan(arreglo_nan_inf))
arreglo_nan

[[False False False]
 [False  True False]
 [ True False False]]


(array([1, 2]), array([1, 0]))

In [32]:
np.isinf(arreglo_nan_inf)
print(np.isinf(arreglo_nan_inf))
arreglo_isinf = np.where(np.isinf(arreglo_nan_inf))
arreglo_isinf

[[False False False]
 [False False False]
 [False False  True]]


(array([2]), array([2]))

In [34]:
np.isneginf(arreglo_nan_inf)
print(np.isneginf(arreglo_nan_inf))
arreglo_isneginf = np.where(np.isneginf(arreglo_nan_inf))
arreglo_isneginf

[[False False False]
 [False False False]
 [False False False]]


(array([], dtype=int64), array([], dtype=int64))

4. Determinar si un arreglo de Numpy contiene valores infinitos.

5. Analizar un arreglo de Numpy y determinar si hay valores NaN

6. Realizar una comparación elemento a elemento de dos arreglos. Contempla mayor, mayor o igual, menor y menor o igual.

## falta

7. Crear un arreglo que contenga los valores 1, 7, 13 y 105, y posteriormente determinar la cantidad de memoria que ocupa el arreglo.

In [49]:
arreglo_vals = np.array([1,7,13,105])
print( "tamaño de un elemento del arreglo:", arreglo_vals.itemsize)
print( "tamaño del arreglo: " ,arreglo_vals.nbytes)

tamaño de un elemento del arreglo: 8
tamaño del arreglo:  32


8. Crear un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.

In [38]:
arreglo_diezzeros = np.zeros([1,10])
arreglo_diezunos = np.ones([1,10])
arreglo_diezcinco = arreglo_diezunos * 5
print (arreglo_diezzeros)
print (arreglo_diezunos)
print (arreglo_diezcinco)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


9. Crear un arreglo que contenga todos los números enteros entre 30 y 70.

In [36]:
print(np.arange(30, 71))

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


10. Crear un arreglo que contenga los números pares entre 30 y 70

In [50]:
print(np.arange(30, 71, 2))

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


11. Crear una matriz identidad de 3x3

In [41]:
matriz_identidad_tres= np.identity(3)
print(matriz_identidad_tres)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Generar un número aleatorio entre 0 y 1

In [43]:
random_numer_zero_uno = print(np.random.random())

0.8572357011106131


13. Crear un arreglo de 15 números aleatorios tomados de una distribución normal estándar.

## falta

14. Crear un arreglo con valores que estén entre 15 y 55, e imprimir todos los valores de éste excepto el primero y el último.

In [46]:
arreglo_ejercicio_ktorce = np.arange(15, 56)

## falta

15. Crear un vector (arreglo) de longitud 10 con valores distribuidos equitativamente entre 5 y 50.

In [51]:
np.linspace(start=5, stop=50, num=10, dtype=int)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

16. Crear un vector con valores de 0 a 20, y cambiar el signo de los números de 9 a 15.

In [56]:
np.linspace(start=0, stop=20, num = 20, dtype=int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 20])

## falta

17. Convertir un arreglo de Numpy a una lista

In [65]:
a = np.array([1,2,3])
print("el tipo de dato es", type(a))
alista = a.tolist()
print("el tipo de dato es", type(alista))

el tipo de dato es <class 'numpy.ndarray'>
el tipo de dato es <class 'list'>


18. Convertir una lista a un arreglo de Numpy

In [64]:
b = ([1,2,3])
print("el tipo de dato es", type(b))
bnumpy = np.asarray(b)
print("el tipo de dato es", type(bnumpy))

el tipo de dato es <class 'list'>
el tipo de dato es <class 'numpy.ndarray'>


19. Verificar los números pares que existen en una matriz y almacenar en otra matriz los resultados de esta comparación lógica.

## falta

20. Encontrar el número de renglones y columnas de una matriz.